### ISSUE TITLE
Spelling in command info

### ISSUE THREAD

**Issue by XargsUK** [Obliviatum/ObliCogs#2]
`matchmaking Let players know you wanna play a certian...`

Should be
`matchmaking Let players know you wanna play a certain...`

**Comment by Obliviatum** [comment]
I see no differences in those lines 😄

**Comment by XargsUK** [comment]
The spelling of "certian" is incorrect. It should be certain :)

**Comment by Obliviatum** [comment]
Whoops, now i see when you have quoted it. My dyslexia has once again failed me.
This has been fixed now
